export const fallbackSpecialists = [
  {
    id: "internal-medicine",
    name: "Penyakit Dalam",
    description: "Latihan kasus penyakit dalam saat data live belum dapat dimuat.",
    icon: "stethoscope",
    status: "available",
    case_count: 1,
  },
  {
    id: "obgyn",
    name: "OBGYN / Reproduksi Wanita",
    description: "Latihan kasus kehamilan dan kesehatan reproduksi saat data live belum dapat dimuat.",
    icon: "venus",
    status: "available",
    case_count: 0,
  },
  {
    id: "pediatrics",
    name: "Kesehatan Anak",
    description: "Latihan kasus anak saat data live belum dapat dimuat.",
    icon: "baby",
    status: "available",
    case_count: 0,
  },
  {
    id: "general-surgery",
    name: "Bedah Umum",
    description: "Latihan kasus bedah umum saat data live belum dapat dimuat.",
    icon: "scissors",
    status: "available",
    case_count: 0,
  },
  {
    id: "anesthesiology",
    name: "Anestesi",
    description: "Latihan kasus anestesi saat data live belum dapat dimuat.",
    icon: "syringe",
    status: "available",
    case_count: 0,
  },
  {
    id: "ophthalmology",
    name: "Kesehatan Mata",
    description: "Latihan kasus mata saat data live belum dapat dimuat.",
    icon: "eye",
    status: "available",
    case_count: 0,
  },
];

export const fallbackCases = [
  {
    id: "internal-medicine-dengue-warning-signs",
    specialist_id: "internal-medicine",
    specialist_name: "Penyakit Dalam",
    patient_name: "Raka",
    patient_age: 23,
    patient_gender: "male",
    chief_complaint: "Demam tinggi sejak 3 hari.",
    triage_note: "Data live belum dapat dimuat. Coba muat ulang jika daftar kasus tidak lengkap.",
    difficulty: "easy",
    condition_badge: "Infeksi akut",
    estimated_duration_minutes: 5,
    patient_avatar_url: "/assets/patients/raka/avatar.png",
    case_thumbnail_url: "/assets/cases/internal-medicine-dengue-warning-signs/thumbnail.png",
    consultation_avatar_url: "/assets/patients/raka/consultation-avatar.png",
    learning_objectives: [
      "Gali pola demam dan tanda bahaya.",
      "Nilai status hidrasi dan perdarahan.",
      "Pilih pemeriksaan awal yang relevan.",
    ],
  },
];
