export const fallbackSpecialists = [
  {
    id: "cardiology",
    name: "Cardiology",
    description: "Latihan konsultasi keluhan jantung dan pembuluh darah.",
    icon: "heart-pulse",
    status: "available",
    case_count: 3,
  },
  {
    id: "pulmonology",
    name: "Pulmonology",
    description: "Kasus respirasi akan dibuka setelah fondasi voice siap.",
    icon: "lungs",
    status: "coming_soon",
    case_count: 0,
  },
  {
    id: "neurology",
    name: "Neurology",
    description: "Kasus neurologi disiapkan untuk fase konten berikutnya.",
    icon: "brain",
    status: "coming_soon",
    case_count: 0,
  },
];

export const fallbackCases = [
  {
    id: "demo",
    specialist_id: "cardiology",
    specialist_name: "Cardiology",
    patient_name: "Maya",
    patient_age: 54,
    patient_gender: "Perempuan",
    chief_complaint: "Nyeri dada kiri sejak 2 jam sebelum datang.",
    triage_note: "Stabil, tampak cemas, perlu gali karakter nyeri dan faktor risiko.",
    difficulty: "easy",
    condition_badge: "Chest pain",
    estimated_duration_minutes: 8,
    is_demo: true,
    learning_objectives: [
      "Gali onset, provokasi, kualitas, radiasi, skala, dan durasi nyeri.",
      "Identifikasi faktor risiko kardiovaskular awal.",
      "Tentukan pemeriksaan awal yang aman sebelum diagnosis akhir.",
    ],
  },
  {
    id: "budi-palpitasi",
    specialist_id: "cardiology",
    specialist_name: "Cardiology",
    patient_name: "Budi",
    patient_age: 42,
    patient_gender: "Laki-laki",
    chief_complaint: "Jantung berdebar setelah minum kopi dan begadang.",
    triage_note: "Hemodinamik stabil, fokus pada red flag, irama, dan konsumsi stimulan.",
    difficulty: "medium",
    condition_badge: "Palpitasi",
    estimated_duration_minutes: 10,
    is_demo: false,
    learning_objectives: [
      "Pisahkan palpitasi benign dari tanda bahaya.",
      "Tanyakan konsumsi stimulan dan pola tidur.",
      "Pilih pemeriksaan awal untuk keluhan berdebar.",
    ],
  },
  {
    id: "siti-sesak",
    specialist_id: "cardiology",
    specialist_name: "Cardiology",
    patient_name: "Siti",
    patient_age: 67,
    patient_gender: "Perempuan",
    chief_complaint: "Sesak saat aktivitas disertai bengkak tungkai.",
    triage_note: "Butuh asesmen gagal jantung, kapasitas fungsional, dan tanda kongesti.",
    difficulty: "hard",
    condition_badge: "Dyspnea",
    estimated_duration_minutes: 12,
    is_demo: false,
    learning_objectives: [
      "Nilai derajat sesak dan gejala kongesti.",
      "Gali komorbid yang memperburuk gagal jantung.",
      "Tentukan prioritas pemeriksaan fisik kardiopulmoner.",
    ],
  },
];
