/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/specialists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Specialists */
        get: operations["public_specialists_api_public_specialists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Case */
        get: operations["public_case_api_public_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/specialists/{specialist_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Specialist Cases */
        get: operations["public_specialist_cases_api_public_specialists__specialist_id__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_api_me_profile_patch"];
        trace?: never;
    };
    "/api/me/onboarding-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboarding Complete */
        post: operations["onboarding_complete_api_me_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specialists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Specialists */
        get: operations["specialists_api_specialists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specialists/{specialist_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Specialist Cases */
        get: operations["specialist_cases_api_specialists__specialist_id__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case Brief */
        get: operations["case_brief_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case Session */
        post: operations["create_case_session_api_case_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Session */
        get: operations["get_case_session_api_case_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Case Session Message */
        post: operations["send_case_session_message_api_case_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/medical-record/opened": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Medical Record */
        post: operations["open_medical_record_api_case_sessions__session_id__medical_record_opened_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/examinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Examination */
        post: operations["select_examination_api_case_sessions__session_id__examinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/timer/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend Timer */
        post: operations["extend_timer_api_case_sessions__session_id__timer_extend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Consultation */
        post: operations["pause_consultation_api_case_sessions__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Consultation */
        post: operations["resume_consultation_api_case_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/end-consultation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Consultation */
        post: operations["end_consultation_api_case_sessions__session_id__end_consultation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-sessions/{session_id}/quiz-submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz */
        post: operations["submit_quiz_api_case_sessions__session_id__quiz_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/case-results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Result */
        get: operations["get_case_result_api_case_results__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Result */
        get: operations["get_history_result_api_history__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Livekit Token */
        post: operations["create_livekit_token_api_livekit_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit/sessions/{session_id}/agent-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voice Agent Context */
        get: operations["get_voice_agent_context_api_livekit_sessions__session_id__agent_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit/sessions/{session_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store Voice Transcript */
        post: operations["store_voice_transcript_api_livekit_sessions__session_id__transcript_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store Voice Event */
        post: operations["store_voice_event_api_livekit_sessions__session_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseBrief */
        CaseBrief: {
            /** Id */
            id: string;
            /** Specialist Id */
            specialist_id: string;
            /** Specialist Name */
            specialist_name: string;
            /** Patient Name */
            patient_name: string;
            /** Patient Age */
            patient_age: number;
            /** Patient Gender */
            patient_gender: string;
            /** Chief Complaint */
            chief_complaint: string;
            /** Triage Note */
            triage_note: string;
            /** Difficulty */
            difficulty: string;
            /** Condition Badge */
            condition_badge: string;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number;
            /** Learning Objectives */
            learning_objectives?: string[];
        };
        /** CaseCard */
        CaseCard: {
            /** Id */
            id: string;
            /** Specialist Id */
            specialist_id: string;
            /** Specialist Name */
            specialist_name: string;
            /** Patient Name */
            patient_name: string;
            /** Patient Age */
            patient_age: number;
            /** Patient Gender */
            patient_gender: string;
            /** Chief Complaint */
            chief_complaint: string;
            /** Triage Note */
            triage_note: string;
            /** Difficulty */
            difficulty: string;
            /** Condition Badge */
            condition_badge: string;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number;
        };
        /** CaseResultResponse */
        CaseResultResponse: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            case: components["schemas"]["CaseBrief"];
            /** Score */
            score: number;
            /** Stars */
            stars: number;
            /** Xp Awarded */
            xp_awarded: number;
            score_breakdown: components["schemas"]["ScoreBreakdownResponse"];
            /** Feedback */
            feedback: {
                [key: string]: unknown;
            };
            /** Answers */
            answers: {
                [key: string]: string;
            };
            /** Created At */
            created_at: string;
            /** Attempt Number */
            attempt_number: number;
            /** Best Score */
            best_score: number;
            /**
             * Is Retry
             * @default false
             */
            is_retry: boolean;
        };
        /** CaseSessionResponse */
        CaseSessionResponse: {
            /** Id */
            id: string;
            case: components["schemas"]["CaseBrief"];
            /**
             * Status
             * @enum {string}
             */
            status: "brief" | "in_consultation" | "quiz" | "completed" | "abandoned";
            /** Remaining Seconds */
            remaining_seconds: number;
            /** Used Extension */
            used_extension: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Medical Record Opened */
            medical_record_opened: boolean;
            medical_record: components["schemas"]["MedicalRecordResponse"];
            /** Examination Options */
            examination_options: components["schemas"]["ExaminationOption"][];
            /** Examinations */
            examinations: components["schemas"]["ExaminationEvent"][];
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
            /** Quiz */
            quiz: components["schemas"]["QuizQuestionResponse"][];
            /** Result Id */
            result_id?: string | null;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "patient" | "system";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /** CreateCaseSessionRequest */
        CreateCaseSessionRequest: {
            /** Case Id */
            case_id: string;
        };
        /** ExaminationEvent */
        ExaminationEvent: {
            /** Id */
            id: string;
            /** Examination Id */
            examination_id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "resulted";
            /** Result */
            result?: string | null;
            /** Requested At */
            requested_at: string;
            /** Resulted At */
            resulted_at: string;
        };
        /** ExaminationOption */
        ExaminationOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Category */
            category: string;
            /** Delay Seconds */
            delay_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Result Id */
            result_id: string;
            /** Session Id */
            session_id: string;
            /** Case Id */
            case_id: string;
            /** Patient Name */
            patient_name: string;
            /** Condition Badge */
            condition_badge: string;
            /** Score */
            score: number;
            /** Stars */
            stars: number;
            /** Created At */
            created_at: string;
            /** Attempt Number */
            attempt_number: number;
            /** Best Score */
            best_score: number;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Total Xp */
            total_xp: number;
            /** Score */
            score: number;
            /** Completed Cases */
            completed_cases: number;
            /** Average Best Score */
            average_best_score: number;
            /** Latest Activity At */
            latest_activity_at?: string | null;
            /** Level */
            level: number;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /** LiveKitTokenRequest */
        LiveKitTokenRequest: {
            /** Session Id */
            session_id: string;
        };
        /** LiveKitTokenResponse */
        LiveKitTokenResponse: {
            /** Token */
            token: string;
            /** Url */
            url: string;
            /** Room Name */
            room_name: string;
            /** Identity */
            identity: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** MeResponse */
        MeResponse: {
            profile: components["schemas"]["Profile"];
            progress: components["schemas"]["ProgressResponse"];
        };
        /** MedicalRecordResponse */
        MedicalRecordResponse: {
            /** Summary */
            summary: string;
            /** History */
            history: string[];
            /** Medications */
            medications: string[];
            /** Allergies */
            allergies: string[];
        };
        /** Profile */
        Profile: {
            /** Id */
            id: string;
            /** Email */
            email?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Is Anonymous
             * @default false
             */
            is_anonymous: boolean;
            /**
             * Onboarding Completed
             * @default false
             */
            onboarding_completed: boolean;
            /**
             * Xp
             * @default 0
             */
            xp: number;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ProgressResponse */
        ProgressResponse: {
            /**
             * Total Xp
             * @default 0
             */
            total_xp: number;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Completed Cases
             * @default 0
             */
            completed_cases: number;
            /**
             * Average Best Score
             * @default 0
             */
            average_best_score: number;
        };
        /** PublicSpecialist */
        PublicSpecialist: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Status */
            status: string;
            /**
             * Case Count
             * @default 0
             */
            case_count: number;
        };
        /** QuizOptionResponse */
        QuizOptionResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** QuizQuestionResponse */
        QuizQuestionResponse: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["QuizOptionResponse"][];
        };
        /** QuizSubmitRequest */
        QuizSubmitRequest: {
            /** Answers */
            answers: {
                [key: string]: string;
            };
        };
        /** ScoreBreakdownResponse */
        ScoreBreakdownResponse: {
            /** Quiz */
            quiz: number;
            /** Interview */
            interview: number;
            /** Examination */
            examination: number;
            /** Medical Record */
            medical_record: number;
            /** Time */
            time: number;
            /** Safety */
            safety: number;
            /** Total */
            total: number;
        };
        /** SelectExaminationRequest */
        SelectExaminationRequest: {
            /** Examination Id */
            examination_id: string;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            user_message: components["schemas"]["ConversationMessage"];
            patient_message: components["schemas"]["ConversationMessage"];
            session: components["schemas"]["CaseSessionResponse"];
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Project
             * @default technofest2026
             */
            project: string;
        };
        /** TimerExtendResponse */
        TimerExtendResponse: {
            /** Remaining Seconds */
            remaining_seconds: number;
            /** Used Extension */
            used_extension: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceAgentContextResponse */
        VoiceAgentContextResponse: {
            /** Session Id */
            session_id: string;
            /** Case Id */
            case_id: string;
            /** Patient Name */
            patient_name: string;
            /** Patient Persona */
            patient_persona: string;
            /** Tts Profile */
            tts_profile: {
                [key: string]: unknown;
            };
            /** Forbidden Terms */
            forbidden_terms: string[];
            /** Allowed Facts */
            allowed_facts: components["schemas"]["VoiceFactResponse"][];
            /** Completed Examinations */
            completed_examinations: components["schemas"]["VoiceExaminationResponse"][];
            /** Safety Rules */
            safety_rules: string[];
            /** Recent Messages */
            recent_messages: components["schemas"]["ConversationMessage"][];
        };
        /** VoiceExaminationResponse */
        VoiceExaminationResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Result */
            result: string;
            /** Score Key */
            score_key?: string | null;
        };
        /** VoiceFactResponse */
        VoiceFactResponse: {
            /** Key */
            key: string;
            /** Response */
            response: string;
        };
        /** VoiceSessionEventRequest */
        VoiceSessionEventRequest: {
            /** Event Type */
            event_type: string;
            /**
             * Severity
             * @default info
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** VoiceSessionEventResponse */
        VoiceSessionEventResponse: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Event Type */
            event_type: string;
            /** Severity */
            severity: string;
            /** Created At */
            created_at: string;
        };
        /** VoiceTranscriptMessage */
        VoiceTranscriptMessage: {
            /** External Id */
            external_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "patient";
            /** Content */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** VoiceTranscriptRequest */
        VoiceTranscriptRequest: {
            /** Messages */
            messages: components["schemas"]["VoiceTranscriptMessage"][];
        };
        /** VoiceTranscriptResponse */
        VoiceTranscriptResponse: {
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    public_specialists_api_public_specialists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSpecialist"][];
                };
            };
        };
    };
    public_case_api_public_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseBrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_specialist_cases_api_public_specialists__specialist_id__cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_profile_api_me_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboarding_complete_api_me_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    specialists_api_specialists_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSpecialist"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    specialist_cases_api_specialists__specialist_id__cases_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                specialist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_brief_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseBrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_session_api_case_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_session_api_case_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_case_session_message_api_case_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_medical_record_api_case_sessions__session_id__medical_record_opened_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_examination_api_case_sessions__session_id__examinations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectExaminationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extend_timer_api_case_sessions__session_id__timer_extend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimerExtendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_consultation_api_case_sessions__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_consultation_api_case_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_consultation_api_case_sessions__session_id__end_consultation_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_api_case_sessions__session_id__quiz_submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_result_api_case_results__result_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_result_api_history__result_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
        };
    };
    create_livekit_token_api_livekit_token_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveKitTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveKitTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_agent_context_api_livekit_sessions__session_id__agent_context_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceAgentContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_voice_transcript_api_livekit_sessions__session_id__transcript_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceTranscriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceTranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_voice_event_api_livekit_sessions__session_id__events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSessionEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSessionEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
